### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by mastizada** [klaviyo/python-klaviyo#27]
I noticed that version 3.0.1 of the project is released, we are currently using 2.0.4 in the project. But as there is no Changelog information I don't know what is changed in this major release version and if I need to do anything before updating to the new version.

**Comment by remstone7** [comment]
@mastizada I can put up a changelog later today - basically the package got completely refactored and no methods from 2.0.4 will work in 3.0.1 - in the README all the methods are shown and how they can be used.  the big change now is instead of doing something like:

`client.get_metrics()`
you would do
`client.Metrics.get_metrics()`

**Comment by mastizada** [comment]
@remstone7 thank you very much for explaining. Yes, that will require to review our klaviyo integration again, will need to delay the upgrade.

**Comment by remstone7** [comment]
added a changelog - we will be using this going forward on all updates - thanks for the call out here, really appreciate it!!!
